services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - test_ljh

  test_ljh:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
